// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop_Mvc.Data;

#nullable disable

namespace Shop_Mvc.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Shop_Mvc.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aging_in_barrel")
                        .HasColumnType("longtext");

                    b.Property<string>("Alcohol")
                        .HasColumnType("longtext");

                    b.Property<string>("Allergen")
                        .HasColumnType("longtext");

                    b.Property<string>("Basis")
                        .HasColumnType("longtext");

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<string>("By_composition")
                        .HasColumnType("longtext");

                    b.Property<string>("Caloric")
                        .HasColumnType("longtext");

                    b.Property<string>("Carbohydrate")
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Composition")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Diaper_size")
                        .HasColumnType("longtext");

                    b.Property<string>("Energy_value")
                        .HasColumnType("longtext");

                    b.Property<string>("Expiration_date")
                        .HasColumnType("longtext");

                    b.Property<string>("Fat")
                        .HasColumnType("longtext");

                    b.Property<string>("Features")
                        .HasColumnType("longtext");

                    b.Property<string>("For_children_with")
                        .HasColumnType("longtext");

                    b.Property<string>("Method")
                        .HasColumnType("longtext");

                    b.Property<string>("Method_of_processing")
                        .HasColumnType("longtext");

                    b.Property<string>("Microelements")
                        .HasColumnType("longtext");

                    b.Property<bool>("OnlyInNovus")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Package_volume")
                        .HasColumnType("longtext");

                    b.Property<string>("Price")
                        .HasColumnType("longtext");

                    b.Property<string>("Promo")
                        .HasColumnType("longtext");

                    b.Property<string>("Protein")
                        .HasColumnType("longtext");

                    b.Property<string>("Quantity_box_package")
                        .HasColumnType("longtext");

                    b.Property<string>("Quantity_in_package")
                        .HasColumnType("longtext");

                    b.Property<string>("Refuel")
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<string>("Sort")
                        .HasColumnType("longtext");

                    b.Property<string>("Storage_conditions")
                        .HasColumnType("longtext");

                    b.Property<string>("Subcategory")
                        .HasColumnType("longtext");

                    b.Property<string>("Temperature")
                        .HasColumnType("longtext");

                    b.Property<string>("Temperature_wine_serving")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type_of_cheese")
                        .HasColumnType("longtext");

                    b.Property<string>("Type_of_sausage")
                        .HasColumnType("longtext");

                    b.Property<string>("Vitamins")
                        .HasColumnType("longtext");

                    b.Property<string>("Wine_classification")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("test");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, null, DelegationModes.ApplyToDatabases);
                });
#pragma warning restore 612, 618
        }
    }
}
